In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
#import linear algebra and data manipulation libraries
import numpy as np
import pandas as pd
from pandas_profiling import ProfileReport

#import standard visualization
import matplotlib.pyplot as plt
import seaborn as sns

#import machine learning models
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [4]:
df = pd.read_csv('African_crises_dataset.csv')

In [5]:
df.head()

country_number country_code  country  year  systemic_crisis  exch_usd  \
0               1          DZA  Algeria  1870                1  0.052264   
1               1          DZA  Algeria  1871                0  0.052798   
2               1          DZA  Algeria  1872                0  0.052274   
3               1          DZA  Algeria  1873                0  0.051680   
4               1          DZA  Algeria  1874                0  0.051308   

   domestic_debt_in_default  sovereign_external_debt_default  \
0                         0                                0   
1                         0                                0   
2                         0                                0   
3                         0                                0   
4                         0                                0   

   gdp_weighted_default  inflation_annual_cpi  independence  currency_crises  \
0                   0.0              3.441456             0                0   
1                   0.0             14.149140             0                0   
2                   0.0             -3.718593             0                0   
3                   0.0             11.203897             0                0   
4                   0.0             -3.848561             0                0   

   inflation_crises banking_crisis  
0                 0         crisis  
1                 0      no_crisis  
2                 0      no_crisis  
3                 0      no_crisis  
4                 0      no_crisis

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   country_number                   1059 non-null   int64  
 1   country_code                     1059 non-null   object 
 2   country                          1059 non-null   object 
 3   year                             1059 non-null   int64  
 4   systemic_crisis                  1059 non-null   int64  
 5   exch_usd                         1059 non-null   float64
 6   domestic_debt_in_default         1059 non-null   int64  
 7   sovereign_external_debt_default  1059 non-null   int64  
 8   gdp_weighted_default             1059 non-null   float64
 9   inflation_annual_cpi             1059 non-null   float64
 10  independence                     1059 non-null   int64  
 11  currency_crises                  1059 non-null   int64  
 12  inflation_crises    

In [7]:
df.describe().T

count          mean            std  \
country_number                   1059.0     35.613787      23.692402   
year                             1059.0   1967.767705      33.530632   
systemic_crisis                  1059.0      0.077432       0.267401   
exch_usd                         1059.0     43.140831     111.475380   
domestic_debt_in_default         1059.0      0.039660       0.195251   
sovereign_external_debt_default  1059.0      0.152975       0.360133   
gdp_weighted_default             1059.0      0.006402       0.043572   
inflation_annual_cpi             1059.0  20848.892444  675727.429176   
independence                     1059.0      0.776204       0.416984   
currency_crises                  1059.0      0.132200       0.349847   
inflation_crises                 1059.0      0.129367       0.335765   

                                         min          25%         50%  \
country_number                      1.000000    15.000000    38.00000   
year                             1860.000000  1951.000000  1973.00000   
systemic_crisis                     0.000000     0.000000     0.00000   
exch_usd                            0.000000     0.195350     0.86840   
domestic_debt_in_default            0.000000     0.000000     0.00000   
sovereign_external_debt_default     0.000000     0.000000     0.00000   
gdp_weighted_default                0.000000     0.000000     0.00000   
inflation_annual_cpi              -28.502137     2.086162     5.76233   
independence                        0.000000     1.000000     1.00000   
currency_crises                     0.000000     0.000000     0.00000   
inflation_crises                    0.000000     0.000000     0.00000   

                                         75%           max  
country_number                     56.000000  7.000000e+01  
year                             1994.000000  2.014000e+03  
systemic_crisis                     0.000000  1.000000e+00  
exch_usd                            8.462750  7.443061e+02  
domestic_debt_in_default            0.000000  1.000000e+00  
sovereign_external_debt_default     0.000000  1.000000e+00  
gdp_weighted_default                0.000000  4.000000e-01  
inflation_annual_cpi               11.644048  2.198970e+07  
independence                        1.000000  1.000000e+00  
currency_crises                     0.000000  2.000000e+00  
inflation_crises                    0.000000  1.000000e+00

In [8]:
from pandas_profiling import ProfileReport
profile = ProfileReport(df, title="African_Crises_Dataset")
profile.to_file("report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [9]:
profile.to_notebook_iframe()

In [10]:
df.isnull().sum()

country_number                     0
country_code                       0
country                            0
year                               0
systemic_crisis                    0
exch_usd                           0
domestic_debt_in_default           0
sovereign_external_debt_default    0
gdp_weighted_default               0
inflation_annual_cpi               0
independence                       0
currency_crises                    0
inflation_crises                   0
banking_crisis                     0
dtype: int64

In [11]:
df['country_number'].value_counts()

country_number
19    155
56    114
70     90
1      85
2      77
40     75
63     75
69     72
38     68
35     67
15     63
45     60
10     58
Name: count, dtype: int64

In [12]:
df['country'].value_counts()

country
Egypt                       155
South Africa                114
Zimbabwe                     90
Algeria                      85
Angola                       77
Morocco                      75
Tunisia                      75
Zambia                       72
Mauritius                    68
Kenya                        67
Ivory Coast                  63
Nigeria                      60
Central African Republic     58
Name: count, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   country_number                   1059 non-null   int64  
 1   country_code                     1059 non-null   object 
 2   country                          1059 non-null   object 
 3   year                             1059 non-null   int64  
 4   systemic_crisis                  1059 non-null   int64  
 5   exch_usd                         1059 non-null   float64
 6   domestic_debt_in_default         1059 non-null   int64  
 7   sovereign_external_debt_default  1059 non-null   int64  
 8   gdp_weighted_default             1059 non-null   float64
 9   inflation_annual_cpi             1059 non-null   float64
 10  independence                     1059 non-null   int64  
 11  currency_crises                  1059 non-null   int64  
 12  inflation_crises    

In [14]:
# Plotting bar plots for each category
categorical_features = [ 'country', 'banking_crisis']
plt.figure(figsize=(25, 35)),
for i in range(0, len(categorical_features)):
    plt.subplot(2, 2, i+1)
    ax = sns.countplot(x = df[categorical_features[i]], palette = 'viridis')
    plt.title(categorical_features[i], fontsize = 20)
    plt.xlabel(' ')
    plt.xticks(rotation=90)

    for p in ax.patches:
        ax.annotate(f'{int(p.get_height())}',
                    (p.get_x() + p.get_width() / 2., p.get_height()),
                    ha = 'center', va= 'bottom', fontsize = 12)
plt.tight_layout()
plt.show()

In [15]:
numerical_features = df.select_dtypes(include='number').columns
numerical_features

Index(['country_number', 'year', 'systemic_crisis', 'exch_usd',
       'domestic_debt_in_default', 'sovereign_external_debt_default',
       'gdp_weighted_default', 'inflation_annual_cpi', 'independence',
       'currency_crises', 'inflation_crises'],
      dtype='object')

In [16]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [17]:
df["banking_crisis"] = label_encoder.fit_transform(df["banking_crisis"])

In [18]:
df['systemic_crisis'].value_counts

<bound method IndexOpsMixin.value_counts of 0       1
1       0
2       0
3       0
4       0
       ..
1054    1
1055    0
1056    0
1057    0
1058    0
Name: systemic_crisis, Length: 1059, dtype: int64>

In [19]:
numerical_features = df.select_dtypes(include='number').columns
correlation = df[numerical_features].corr().apply(abs)
correlation = correlation[['banking_crisis']].sort_values(['banking_crisis'], ascending=False)
correlation

# Set a threshold for low correlation (e.g., absolute correlation < 0.1)
threshold = 0.2

# Filter the column names that have an absolute correlation with SalePrice below the threshold
low_corr_columns = correlation[correlation['banking_crisis']< threshold].index.tolist()

# Print the list of columns with low correlation
print(f"Columns with correlation less than {threshold}:\n", low_corr_columns)

Columns with correlation less than 0.2:
 ['exch_usd', 'currency_crises', 'independence', 'inflation_annual_cpi', 'gdp_weighted_default', 'country_number']


In [20]:
df = df.drop(columns=low_corr_columns)

In [21]:
df = df.drop("country_code", axis=1)

In [22]:
df.head()

country  year  systemic_crisis  domestic_debt_in_default  \
0  Algeria  1870                1                         0   
1  Algeria  1871                0                         0   
2  Algeria  1872                0                         0   
3  Algeria  1873                0                         0   
4  Algeria  1874                0                         0   

   sovereign_external_debt_default  inflation_crises  banking_crisis  
0                                0                 0               0  
1                                0                 0               1  
2                                0                 0               1  
3                                0                 0               1  
4                                0                 0               1

In [23]:
df = df.join(pd.get_dummies(df.country))
df = df.drop("country", axis=1)

In [24]:
df.head()

year  systemic_crisis  domestic_debt_in_default  \
0  1870                1                         0   
1  1871                0                         0   
2  1872                0                         0   
3  1873                0                         0   
4  1874                0                         0   

   sovereign_external_debt_default  inflation_crises  banking_crisis  Algeria  \
0                                0                 0               0     True   
1                                0                 0               1     True   
2                                0                 0               1     True   
3                                0                 0               1     True   
4                                0                 0               1     True   

   Angola  Central African Republic  Egypt  Ivory Coast  Kenya  Mauritius  \
0   False                     False  False        False  False      False   
1   False                     False  False        False  False      False   
2   False                     False  False        False  False      False   
3   False                     False  False        False  False      False   
4   False                     False  False        False  False      False   

   Morocco  Nigeria  South Africa  Tunisia  Zambia  Zimbabwe  
0    False    False         False    False   False     False  
1    False    False         False    False   False     False  
2    False    False         False    False   False     False  
3    False    False         False    False   False     False  
4    False    False         False    False   False     False

In [25]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [69]:
df_encoded = pd.read_csv("African_crises_dataset.csv")

In [27]:
# Features and target
X = df.drop('systemic_crisis', axis=1)
y = df['systemic_crisis']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)

In [29]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit and transform the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the test data
X_test_scaled = scaler.transform(X_test)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification}')

Accuracy: 0.9858490566037735
Confusion Matrix:
[[195   0]
 [  3  14]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       195
           1       1.00      0.82      0.90        17

    accuracy                           0.99       212
   macro avg       0.99      0.91      0.95       212
weighted avg       0.99      0.99      0.99       212



In [38]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification}')

Accuracy: 0.9952830188679245
Confusion Matrix:
[[194   1]
 [  0  17]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       195
           1       0.94      1.00      0.97        17

    accuracy                           1.00       212
   macro avg       0.97      1.00      0.98       212
weighted avg       1.00      1.00      1.00       212



In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification}')

Accuracy: 0.9952830188679245
Confusion Matrix:
[[194   1]
 [  0  17]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       195
           1       0.94      1.00      0.97        17

    accuracy                           1.00       212
   macro avg       0.97      1.00      0.98       212
weighted avg       1.00      1.00      1.00       212



In [41]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = SVC()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification}')

Accuracy: 0.9198113207547169
Confusion Matrix:
[[195   0]
 [ 17   0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       195
           1       0.00      0.00      0.00        17

    accuracy                           0.92       212
   macro avg       0.46      0.50      0.48       212
weighted avg       0.85      0.92      0.88       212



In [42]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = KNeighborsClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification}')

Accuracy: 0.9481132075471698
Confusion Matrix:
[[194   1]
 [ 10   7]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       195
           1       0.88      0.41      0.56        17

    accuracy                           0.95       212
   macro avg       0.91      0.70      0.77       212
weighted avg       0.94      0.95      0.94       212



In [43]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = GaussianNB()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Confusion Matrix:\n{confusion}')
print(f'Classification Report:\n{classification}')

Accuracy: 0.6037735849056604
Confusion Matrix:
[[111  84]
 [  0  17]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.57      0.73       195
           1       0.17      1.00      0.29        17

    accuracy                           0.60       212
   macro avg       0.58      0.78      0.51       212
weighted avg       0.93      0.60      0.69       212

